[package]
authors = ["Alexander Regueiro <alex@noldorin.com>"]
edition = "2021"
name = "kache"
version = "0.1.0"

[dependencies]
anyhow = "1.0.68"
clap = {version = "4.1.2", features = ["derive", "unicode", "wrap_help"]}
humantime = "2.1.0"
lazy_static = "1.4.0"
log = "0.4.17"
speedy = "0.8.5"
